### ISSUE TITLE
archive this package

### ISSUE THREAD

**Issue by maelle** [ropensci-archive/rodev#43]

**Comment by mpadge** [comment]
# TODO

Move these to `pkgcheck` first:

- [ ] `use_docs_link()`
- [ ] `read_pkg_guide()`

**Comment by maelle** [comment]
check for badges after review

**Comment by maelle** [comment]
https://github.com/ropensci-review-tools/pkgcheck/pull/118

**Comment by maelle** [comment]
https://github.com/ropensci/roweb3/blob/master/README.md

**Comment by maelle** [comment]
Doc link doesn't sound that much useful to have as function.
